sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t zepp/cestio .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$HUB_USER" -p="$HUB_PASS"
    TAG=$(grep "ENV HUGO_BUILD" Dockerfile | awk 'NF>1{print $NF}')
    docker tag zepp/cestio zepp/cestio:$TAG
    docker push zepp/cestio:$TAG
    docker push zepp/cestop
  fi