sudo: required
services:
- docker
language: bash
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - docker build -t zepp/cestio .
  # push image
  - docker login -u="$HUB_USER" -p="$HUB_PASS"
  - docker tag zepp/cestio zepp/cestio:latest
  - docker push zepp/cestio:latest
