sudo: required
services:
  - docker
language: bash
script:
  - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
  - export REPO=zepp/cestio
  # prepare qemu for ARMv7
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t $REPO:$TAG .

after_success:
  - docker login -u="$HUB_USER" -p="$HUB_PASS"
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
    docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER;
    docker push $REPO:$TRAVIS_BUILD_NUMBER;
    fi 
  - docker push $REPO:$TAG

notifications:
  slack: 
    rooms: 
      - tech-hort:SPDnq642sujLV8S2mV34ONip#github
    template:
      - "%{repository} (%{commit}) : %{message} "
      - "Build details: %{build_url}"
      - "Build number: %{build_number}"
      - "Commit message: %{commit_message}"
      - "Runtime: %{elapsed_time}"
      - "Result: %{result}"