baseURL = "http://cest.io"
languageCode = "de-de"
title = "cest.io"
disqusShortname = "cest-io"
paginate = 5

[params]
  ordersectionsby = "weight"
  disableSearch = false
  themeVariant = "mine"
  editURL = "https://github.com/zepptron/cestio/tree/master/www/content/"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]] 
  pre = "<h3>Other</h3>"
  name = "<i class='fa fa-github'></i> Github"
  url = "https://github.com/zepptron"
  weight = -2

[[menu.shortcuts]] 
  name = "<i class='fa fa-spotify'></i> Spotify"
  url = "https://open.spotify.com/user/recyco"
  weight = -2

[[menu.shortcuts]] 
  name = "<i class='fa fa-slack'></i> Slack"
  url = "http://cest.io/slack"
  weight = -2

