baseURL = "http://cest.io"
languageCode = "de-de"
title = "cest.io"
disqusShortname = "cest-io"
paginate = 5

[params]
  ordersectionsby = "weight"
  disableSearch = false
  themeVariant = "mine"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
  pre = "<h3>Navigation</h3>"
  name = "<i class='fa fa-home'></i> About"
  url = "/"
  weight = -3

[[menu.shortcuts]] 
  name = "<i class='fa fa-github'></i> Github"
  identifier = "ds"
  url = "https://github.com/zepptron"
  weight = -2
