baseURL = "http://cest.io"
languageCode = "de-de"
title = "cest.io"
disqusShortname = "cest-io"
theme = "learn"
paginate = 5

[params]
  ordersectionsby = "weight"
  disableSearch = false
  themeVariant = "mine"

[outputs]
home = [ "HTML", "RSS", "JSON"]
